name: Playwright GAD tests - docker image

on:
#  push:
#    branches: ["main"]
#  pull_request:
#    branches: ["main"]
  workflow_dispatch:
  
permissions:
  contents: read
  checks: write
  id-token: write  
  
jobs:
  gad-tests:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    services:
      gad:
        image: jaktestowac/gad:latest
        ports:
          - 3000:3000
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
          registry-url: "https://npm.pkg.github.com"
          cache-dependency-path: "**/package-lock.json"
          
      - name: Cache Node Modules
        uses: actions/cache@v4
        id: node-modules-cache
        with:
          path: |
            node_modules
          key: node_modules-${{ hashFiles('package-lock.json') }}    
          
      - name: Install npm dependencies
        if: steps.node-modules-cache.outputs.cache-hit != 'true'  
        run: npm ci       
        
      - name: Get installed Playwright version
        id: playwright-version
        run: echo "PLAYWRIGHT_VERSION=$(node -e "console.log(require('./package-lock.json').packages['node_modules/@playwright/test'].version)")" >> $GITHUB_ENV    
     
      - name: Cache Playwright binaries
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}       
    
      - name: Install Playwright Browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'      
        run: npx playwright install --with-deps   
   
      - name: Check GAD status
        run: |
          curl ${{ vars.BASE_URL }}/api/about
          curl ${{ vars.BASE_URL }}/api/health
   
      - name: Run Playwright Tests
        env:
          BASE_URL: ${{ vars.BASE_URL }}
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
        run: |
          npm run test   
          
      - name: Archive Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            **/playwright-report/** 
            **/test-results/**
            
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: always()
        with:
          report_paths: '**/playwright-report/results.xml'
          
      - name: Deploy report to github pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./playwright-report
          publish_branch: gh-pages
